# Generated by Django 3.2.2 on 2021-05-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('Elektronik', 'Elektronik'), ('Transportasi', 'Transportasi'), ('Furnitur', 'Furnitur'), ('Lain-lain', 'Lain-lain')], default='Elektronik', max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('merek', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
            ],
            options={
                'db_table': 'barang',
            },
        ),
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gedung',
            },
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_pengenal', models.PositiveBigIntegerField(unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'peminjam',
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('id_gedung', models.ForeignKey(db_column='id_gedung', default='', on_delete=django.db.models.deletion.CASCADE, to='SMIK.gedung')),
            ],
            options={
                'db_table': 'ruangan',
            },
        ),
        migrations.CreateModel(
            name='FormPinjam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_peminjaman', models.PositiveBigIntegerField(unique=True)),
                ('tanggal_pinjam', models.DateTimeField()),
                ('tanggal_kembali', models.DateTimeField()),
                ('jumlah_pinjam', models.PositiveIntegerField()),
                ('scan_form', models.CharField(max_length=50)),
                ('id_barang', models.ForeignKey(db_column='id_barang', on_delete=django.db.models.deletion.CASCADE, to='SMIK.barang')),
                ('id_peminjam', models.ForeignKey(db_column='id_peminjam', on_delete=django.db.models.deletion.CASCADE, to='SMIK.peminjam')),
            ],
            options={
                'db_table': 'form_pinjam',
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='id_ruangan',
            field=models.ForeignKey(db_column='id_ruangan', default='', on_delete=django.db.models.deletion.CASCADE, to='SMIK.ruangan'),
        ),
    ]
