# Generated by Django 3.2.2 on 2021-05-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMIK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpinjam',
            name='id_barang',
            field=models.ForeignKey(db_column='id_barang', default='', on_delete=django.db.models.deletion.CASCADE, to='SMIK.barang'),
        ),
        migrations.AlterField(
            model_name='formpinjam',
            name='no_peminjaman',
            field=models.CharField(max_length=50),
        ),
    ]
